// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Database;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1m,
                            RoleId = 1m
                        },
                        new
                        {
                            UserId = 1m,
                            RoleId = 2m
                        },
                        new
                        {
                            UserId = 2m,
                            RoleId = 2m
                        });
                });

            modelBuilder.Entity("UserService.Database.Models.RoleModel", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2m,
                            Name = "Normal user"
                        });
                });

            modelBuilder.Entity("UserService.Database.Models.UserModel", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Username");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            FirstName = "System",
                            LastName = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEJt9NjjgjE/IFWCEo/q2keV55MsU5jsJXY8Zp5vpaDHWZIA/fCrYK5Z4JFE2l66iFA==",
                            Username = "systemadmin"
                        },
                        new
                        {
                            Id = 2m,
                            FirstName = "Normal",
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEOzCrut9AdD8ITnTfSa+DZbe+oH+BGiAZvlLHYGWOgqAJm3mv2bVqQvxxau2xunA4A==",
                            Username = "normaluser"
                        });
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("UserService.Database.Models.RoleModel", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Database.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
